set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
############## clock define##################
create_clock -period 5.000 [get_ports sys_clk_p]
set_property PACKAGE_PIN AE5 [get_ports sys_clk_p]
set_property IOSTANDARD DIFF_SSTL12 [get_ports sys_clk_p]

##############AN9767#############################
set_property PACKAGE_PIN AG13 [get_ports {da1_data[0]}]
set_property PACKAGE_PIN AH13 [get_ports {da1_data[1]}]
set_property PACKAGE_PIN AB10 [get_ports {da1_data[2]}]
set_property PACKAGE_PIN AB9	 [get_ports {da1_data[3]}]
set_property PACKAGE_PIN W10	 [get_ports {da1_data[4]}]
set_property PACKAGE_PIN Y10	 [get_ports {da1_data[5]}]
set_property PACKAGE_PIN W12	 [get_ports {da1_data[6]}]
set_property PACKAGE_PIN W11	 [get_ports {da1_data[7]}]
set_property PACKAGE_PIN W14	 [get_ports {da1_data[8]}]
set_property PACKAGE_PIN W13	 [get_ports {da1_data[9]}]
set_property PACKAGE_PIN AB15 [get_ports {da1_data[10]}]
set_property PACKAGE_PIN AB14 [get_ports {da1_data[11]}]
set_property PACKAGE_PIN AF11 [get_ports {da1_data[12]}]
set_property PACKAGE_PIN AG11 [get_ports {da1_data[13]}]
set_property PACKAGE_PIN AA12	 [get_ports {da1_wrt}]
set_property PACKAGE_PIN Y12 [get_ports {da1_clk}]


set_property IOSTANDARD LVCMOS33 [get_ports {da1_data[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da1_wrt}]
set_property IOSTANDARD LVCMOS33 [get_ports {da1_clk}]

set_property PACKAGE_PIN AE14 [get_ports {da2_clk}]
set_property PACKAGE_PIN AE15 [get_ports {da2_wrt}]
set_property PACKAGE_PIN AC12 [get_ports {da2_data[0]}]
set_property PACKAGE_PIN AD12 [get_ports {da2_data[1]}]
set_property PACKAGE_PIN AD11 [get_ports {da2_data[2]}]
set_property PACKAGE_PIN AD10 [get_ports {da2_data[3]}]
set_property PACKAGE_PIN AB11 [get_ports {da2_data[4]}]
set_property PACKAGE_PIN AC11 [get_ports {da2_data[5]}]
set_property PACKAGE_PIN AG14 [get_ports {da2_data[6]}]
set_property PACKAGE_PIN AH14 [get_ports {da2_data[7]}]
set_property PACKAGE_PIN Y14	 [get_ports {da2_data[8]}]
set_property PACKAGE_PIN Y13	 [get_ports {da2_data[9]}]
set_property PACKAGE_PIN AC14 [get_ports {da2_data[10]}]
set_property PACKAGE_PIN AC13 [get_ports {da2_data[11]}]
set_property PACKAGE_PIN AD15 [get_ports {da2_data[12]}]
set_property PACKAGE_PIN AD14 [get_ports {da2_data[13]}]

set_property IOSTANDARD LVCMOS33 [get_ports {da2_clk}]
set_property IOSTANDARD LVCMOS33 [get_ports {da2_wrt}]
set_property IOSTANDARD LVCMOS33 [get_ports {da2_data[*]}]

