proc set_ps_config {bd_cell_name} {
set_property -dict [list CONFIG.PSU__CAN0__PERIPHERAL__ENABLE {1}  \
     CONFIG.PSU__CAN0__PERIPHERAL__IO {MIO 38 .. 39}  \
     CONFIG.PSU__CAN1__PERIPHERAL__ENABLE {1}  \
     CONFIG.PSU__CAN1__PERIPHERAL__IO {MIO 32 .. 33}  \
     CONFIG.PSU__DPAUX__PERIPHERAL__IO {MIO 27 .. 30}  \
     CONFIG.PSU__ENET2__PERIPHERAL__ENABLE {0}  \
     CONFIG.PSU__ENET3__PERIPHERAL__ENABLE {1}  \
     CONFIG.PSU__ENET3__GRP_MDIO__ENABLE {1}  \
     CONFIG.PSU__GPIO1_MIO__PERIPHERAL__ENABLE {1}  \
     CONFIG.PSU__I2C1__PERIPHERAL__ENABLE {1}  \
     CONFIG.PSU__I2C1__PERIPHERAL__IO {MIO 24 .. 25}  \
     CONFIG.PSU__PCIE__PERIPHERAL__ENABLE {1}  \
     CONFIG.PSU__PCIE__PERIPHERAL__ROOTPORT_IO {MIO 37}  \
     CONFIG.PSU__USB0__REF_CLK_SEL {Ref Clk1}  \
     CONFIG.PSU__PCIE__DEVICE_PORT_TYPE {Root Port}  \
     CONFIG.PSU__PCIE__BAR0_ENABLE {1}  \
     CONFIG.PSU__PCIE__CLASS_CODE_SUB {0x04}  \
     CONFIG.SUBPRESET1 {DDR4_MICRON_MT40A256M16GE_083E}  \
     CONFIG.PSU__QSPI__PERIPHERAL__ENABLE {1}  \
     CONFIG.PSU__QSPI__PERIPHERAL__DATA_MODE {x4}  \
     CONFIG.PSU__QSPI__GRP_FBCLK__ENABLE {1}  \
     CONFIG.PSU__SD0__PERIPHERAL__ENABLE {1}  \
     CONFIG.PSU__SD0__SLOT_TYPE {eMMC}  \
     CONFIG.PSU__SD0__RESET__ENABLE {1}  \
     CONFIG.PSU__SD1__PERIPHERAL__ENABLE {1}  \
     CONFIG.PSU__SD1__PERIPHERAL__IO {MIO 46 .. 51}  \
     CONFIG.PSU__SD1__GRP_CD__ENABLE {1}  \
     CONFIG.PSU__SD1__SLOT_TYPE {SD 2.0}  \
     CONFIG.PSU__TTC0__PERIPHERAL__ENABLE {1}  \
     CONFIG.PSU__TTC1__PERIPHERAL__ENABLE {1}  \
     CONFIG.PSU__TTC2__PERIPHERAL__ENABLE {1}  \
     CONFIG.PSU__TTC3__PERIPHERAL__ENABLE {1}  \
     CONFIG.PSU__DDRC__DEVICE_CAPACITY {8192 MBits}  \
     CONFIG.PSU__DDRC__ROW_ADDR_COUNT {16}  \
     CONFIG.PSU__UART0__PERIPHERAL__ENABLE {1}  \
     CONFIG.PSU__UART0__PERIPHERAL__IO {MIO 42 .. 43}  \
     CONFIG.PSU__USB0__PERIPHERAL__ENABLE {1}  \
     CONFIG.PSU__USB0__RESET__ENABLE {1}  \
     CONFIG.PSU__USB0__RESET__IO {MIO 31}  \
     CONFIG.PSU__USB__RESET__MODE {Shared MIO Pin}  \
     CONFIG.PSU__USB3_0__PERIPHERAL__ENABLE {1}  \
     CONFIG.PSU__USB3_0__PERIPHERAL__IO {GT Lane1}  \
     CONFIG.PSU_BANK_0_IO_STANDARD {LVCMOS18}  \
     CONFIG.PSU_BANK_1_IO_STANDARD {LVCMOS18}  \
     CONFIG.PSU_BANK_2_IO_STANDARD {LVCMOS18}  \
     CONFIG.PSU__DISPLAYPORT__PERIPHERAL__ENABLE {1}  \
     CONFIG.PSU__CRF_APB__DP_VIDEO_REF_CTRL__SRCSEL {VPLL}  \
     CONFIG.PSU__CRF_APB__DP_AUDIO_REF_CTRL__SRCSEL {RPLL}  \
     CONFIG.PSU__CRF_APB__DP_STC_REF_CTRL__SRCSEL {RPLL}  \
     CONFIG.PSU__CRF_APB__TOPSW_MAIN_CTRL__SRCSEL {APLL}  \
     CONFIG.PSU__CRL_APB__SDIO0_REF_CTRL__SRCSEL {IOPLL}  \
     CONFIG.PSU__CRL_APB__SDIO1_REF_CTRL__SRCSEL {IOPLL}] [get_bd_cells $bd_cell_name]
}